// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuW4u6DxPlPicT6xuzv0yk_OEWOfHStYQ',
    appId: '1:16094654388:ios:f3f6d655b0d48c3c3b0ce1',
    messagingSenderId: '16094654388',
    projectId: 'mis-meals-app-verica-2e919',
    storageBucket: 'mis-meals-app-verica-2e919.firebasestorage.app',
    iosBundleId: 'com.example.restaurantmenu.homework2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQBUl7MVl4CwFo9DqRLXcEjSWIfY1Jt6s',
    appId: '1:16094654388:web:82f87b4b17b3dd9f3b0ce1',
    messagingSenderId: '16094654388',
    projectId: 'mis-meals-app-verica-2e919',
    authDomain: 'mis-meals-app-verica-2e919.firebaseapp.com',
    storageBucket: 'mis-meals-app-verica-2e919.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQBUl7MVl4CwFo9DqRLXcEjSWIfY1Jt6s',
    appId: '1:16094654388:web:82f87b4b17b3dd9f3b0ce1',
    messagingSenderId: '16094654388',
    projectId: 'mis-meals-app-verica-2e919',
    authDomain: 'mis-meals-app-verica-2e919.firebaseapp.com',
    storageBucket: 'mis-meals-app-verica-2e919.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuW4u6DxPlPicT6xuzv0yk_OEWOfHStYQ',
    appId: '1:16094654388:ios:f3f6d655b0d48c3c3b0ce1',
    messagingSenderId: '16094654388',
    projectId: 'mis-meals-app-verica-2e919',
    storageBucket: 'mis-meals-app-verica-2e919.firebasestorage.app',
    iosBundleId: 'com.example.restaurantmenu.homework2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAainQ0dlFGq_Zp1ntBJQLDZ6_xDGQcWfM',
    appId: '1:16094654388:android:4d63a2a0713ca0953b0ce1',
    messagingSenderId: '16094654388',
    projectId: 'mis-meals-app-verica-2e919',
    storageBucket: 'mis-meals-app-verica-2e919.firebasestorage.app',
  );

}